nginx:
  image: "nginx:1.9"
  ports:
    - 80:80
    - 443:443
  links:
    - registry:registry
    # - jenkins:jenkins
    - drone:drone
  volumes:
    - ./data_nginx/:/etc/nginx/conf.d:ro

registry:
  image: registry:2
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
  volumes:
    - ./data_registry:/registry_data
# jenkins:
#   image: "jenkins:1.642.3"
#   ports:
#     - 50000:50000
#   volumes:
#     - ./data_jenkins:/var/jenkins_home


drone:
  image: "drone/drone:0.4"
  volumes:
    - /data_drone:/var/lib/drone
    - /var/run/docker.sock:/var/run/docker.sock
  # ports: 
  #  - 8001:8000
  environment:
    REMOTE_DRIVER: gitlab
    REMOTE_CONFIG: "https://git.octopuscreative.com?client_id=701b1ab7166eea684c467c38630a29e3f80553e0473491c1f6e2742be1388304&client_secret=78fa8b599aae1259d866acfc2eb19c5f835f0188059ba79555d8b626019d1f00&skip_verify=true"
    # REMOTE_DRIVER: github
    # REMOTE_CONFIG: "https://github.com?client_id=d22967983f8e4c0a4f58&client_secret=29fb94df262a32a167adecf691486c842dad46cd"
    # REMOTE_CONFIG: "https://github.com?client_id=e717754c2f131971bae4&client_secret=OCKXMYVDFDS2FZYFXOSEGMMD2PN3QZ6TAXZ7LA64EARRL4BPPYIA%3D%3D%3D%3D"
    DATABASE_DRIVER: sqlite3
    DATABASE_CONFIG: /var/lib/drone/drone.sqlite
