nginx:
  image: "nginx:1.9"
  ports:
    - 80:80
    - 443:443
  links:
    - registry:registry
    # - jenkins:jenkins
    - drone:drone
    - gogs:gogs
  volumes:
    - ./data_nginx/:/etc/nginx/conf.d:ro

registry:
  image: registry:2
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
  volumes:
    - ./data_registry:/registry_data
# jenkins:
#   image: "jenkins:1.642.3"
#   ports:
#     - 50000:50000
#   volumes:
#     - ./data_jenkins:/var/jenkins_home

gogs: 
  image: "gogs/gogs"
  # ports:
    # - 10022:22
    # - 10080:3000 
  volumes:
    - ./data_gogs:/data gogs/gogs


drone:
  image: "drone/drone:0.4"
  volumes:
    - /data_drone:/var/lib/drone
    - /var/run/docker.sock:/var/run/docker.sock
  # ports: 
  #  - 8001:8000
  environment:
    REMOTE_DRIVER: github
    REMOTE_CONFIG: "https://github.com?client_id=d22967983f8e4c0a4f58&client_secret=29fb94df262a32a167adecf691486c842dad46cd"
    # REMOTE_CONFIG: "https://github.com?client_id=e717754c2f131971bae4&client_secret=OCKXMYVDFDS2FZYFXOSEGMMD2PN3QZ6TAXZ7LA64EARRL4BPPYIA%3D%3D%3D%3D"
    DATABASE_DRIVER: sqlite3
    DATABASE_CONFIG: /var/lib/drone/drone.sqlite
